name: Publish Plugin

on:
  workflow_dispatch:      
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: logseq-plugin-colored-threads

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Bun 1.0.x
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.x

    - name: Run install
      id: install
      run: bun install

    - name: Build package bundle
      id: build
      run: bun build
      
    - name: Zip build
      id: zip
      run: |
        mv dist ${{ env.PLUGIN_NAME }}
        cp example.png settings.png logo.svg README.md package.json ${{ env.PLUGIN_NAME }}
        zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
        tar -cvzf ${{ env.PLUGIN_NAME }}.tgz ${{ env.PLUGIN_NAME }}
        ls        
        echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

    - name: Create Release
      uses: ncipollo/release-action@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}
      with:
        allowUpdates: true
        draft: false
        prerelease: false

    - name: Upload zip file
      id: upload_zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.PLUGIN_NAME }}.zip
        asset_name: ${{ env.PLUGIN_NAME }}-${{ github.ref }}.zip
        asset_content_type: application/zip

    - name: Upload package.json
      id: upload_metadata
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./package.json
        asset_name: package.json
        asset_content_type: application/json